# Example file for TR++ chat (https://t.me/telran)

question: "Добро пожаловать! У вас есть 5 минут чтобы доказать, что вы не спамер!\n\nСколько плюсов в названии группы?"

button_options:
  - title: 1
    correct: false
  - title: 2
    correct: true
  - title: 3
    correct: false
  - title: 4
    correct: false
  - title: 5
    correct: false

enable_wrong_answers: true

wrong_answers:
    - "Я бы на твоем месте застрелился."
    - "Ну нажал. Легче стало?"
    - "Угадай, кто только что подтвердил что он дегенерат?"
    - "Чтоб у тебя этот палец отсох!"
    - "Тест на пидора успешно пройден. Поздравляем, ты пидор! "
    - "Ты не спамер, ты сильно хуже. Ты мудак с геном петросяна."
    - "За тобой уже выехали, шутист."
    - "Анус себе потыкай, пёс!"
    - "Игорь, ты?"
    - "Я смотрю, папа не старался, и ты теперь за него компенсируешь, постоянно тыкая все подряд?"
    - "Таким как ты нужно гвоздь в голову вбивать при рождении."
    - "И ты видимо считаешь, что это афигенно смешно?"
    - "Так и запишем: помогал ботам."
    - "Хочешь, всем расскажу, чем ты тут занимаешься?"
    - "Не твоя, вот ты и бесишься."
    - "Ваш диагноз - патологическая гипоэнцефалокарния."
    - "Чтоб тебе всю жизнь на одну и ту же кнопку жать."
    - "Не думал о карьере фронтендера? Ты бы подошел."
    - "Дружище, это не лифт, здесь каждый сам за себя."
    - "У меня во дворе за такое убивают нахуй."
    - "Еще раз – и ты пидарас."
    - "Кролик с аватары этого чата гораздо умнее тебя. Гораздо умнее. Гораздо!"
    - "Ты кажется можешь посоревноваться в интеллекте с хасой, которую кролик с аватары ест."
    - "Нет, ну вы посмотрите на этого поца. Тыкает куда ни попадя!"
    - "А тот кто будет тыкать эту кнопку - тому фурункул вскочит на живот!"
    - "Повар спрашивает повара: нахуя ты тыкаешь эту кнопку?"

